### ISSUE TITLE
vnc port number and ip address please?

### ISSUE THREAD

**Issue by improvisor40** [CypherpunkArmory/FoxBox#3]
Please I kinda want to connect via an external client as I can't seem to save my default vnc scaling and input mode with its built in client.
But with bvnc, (nice app by the way!!), I can save default settings configuration, so please help me with its ip and port number.

**Comment by KhalfaniW** [comment]
This app is a full Linux VM: you can do whatever you want.   

The Foxbox VM uses Tightvnc server

If you want to use an external client you can start a new vnc server .

### **Steps**

1.  run `$ vncserver :99 `
   This will start a new vncserver on port :5999

2.  use `$ vncpasswd` to change the password for the vncserver
    We currently have to do this becuase we don't know what the FoxBox vnc password is. 
    Note: this will require you to enter this password when you open FoxBox to view the original vncviewer

3. Close firefox
     It can run on only one vncserver instance at a time.

6.  Go to localhost:5999 in the other vncviewer and enter your password 


7. Open firefox

Right click in the new vncviewer to open a context menu and click 'Web browser' 
Or run `DISPLAY=:99 firefox` in the terminal

**Comment by improvisor40** [comment]
OK, thanks it works.
